[package]
name = "calculable-shape"
version = "0.1.0"
authors = ["Ian Yan <ian@adhub.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
